<a href="https://colab.research.google.com/github/otorregrosa/Coding-Propositional-Logic/blob/main/Lab6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1



In [5]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [21]:
def mat_desc(x):
    print(x)
    if x.size > 0:
        is_square = True if x.shape[0] == x.shape[1] else False 
        print("Shape, Size: ", x.shape)
        print("Rank: ", x.ndim)
        print("Is a Square Matrix: ", is_square)
        is_zeros = not np.any(x)
        print("Is a Zero Matrix: ", is_zeros)
        is_ones = np.all((x == 1))
        print("Is an Ones Matrix: ", is_ones)
      
        rows = len(x);  
        cols = len(x[0]);  
        is_identity=True
       
        for i in range(0, rows):  
                for j in range(0, cols):  
                    if(i == j and x[i][j] != 1):  
                        is_identity = False
                    if(i != j and x[i][j] != 0):  
                        is_identity = False
        if is_identity:
            print("Is an Identity Matrix")
        else:
            print("Is not an Identity Matrix")
        print("Matrix is not Null")
    else:   
        print("Shape/Size: n/a")
        print("Rank: n/a")
        print("Is a Square Matrix: n/a")
        print("Is a Zero Matrix: n/a")
        print("Is an Ones Matrix: n/a")
        print("Is an Identity Matrix: n/a")
        print('Matrix is Null')

In [30]:
A = np.array([[1,2,3],[1,3,5],[2,4,6]])
B = np.array([[7,2,8],[9,1,9],[2,0,0]])
C = np.array([[3,9,5],[7,7,7],[4,8,2]])
D = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])
E = np.array([])

In [31]:
mat_desc(A)

[[1 2 3]
 [1 3 5]
 [7 2 8]]
Shape, Size:  (3, 3)
Rank:  2
Is a Square Matrix:  True
Is a Zero Matrix:  False
Is an Ones Matrix:  False
Is not an Identity Matrix
Matrix is not Null


In [32]:
mat_desc(B)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Shape, Size:  (3, 3)
Rank:  2
Is a Square Matrix:  True
Is a Zero Matrix:  True
Is an Ones Matrix:  False
Is not an Identity Matrix
Matrix is not Null


In [33]:
mat_desc(C)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
Shape, Size:  (3, 3)
Rank:  2
Is a Square Matrix:  True
Is a Zero Matrix:  False
Is an Ones Matrix:  True
Is not an Identity Matrix
Matrix is not Null


In [34]:
mat_desc(D)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
Shape, Size:  (3, 3)
Rank:  2
Is a Square Matrix:  True
Is a Zero Matrix:  False
Is an Ones Matrix:  False
Is an Identity Matrix
Matrix is not Null


In [35]:
mat_desc(E)

[]
Shape/Size: n/a
Rank: n/a
Is a Square Matrix: n/a
Is a Zero Matrix: n/a
Is an Ones Matrix: n/a
Is an Identity Matrix: n/a
Matrix is Null


Task 2

In [15]:
def mat_operations(x,y):
    print("Array 1: \n", x)
    print("\nArray 2: \n", y)
    print("\nIs Scalar(Array1): ",isinstance(x, (int, float, complex, bytes)))
    print("\nIs Scalar(Array2): ",isinstance(y, (int, float, complex, bytes)))
    check_scalar1 = isinstance(x, (int, float, complex, bytes))
    check_scalar2 = isinstance(y, (int, float, complex, bytes))
    check_array1 = isinstance(x, np.ndarray)
    check_array2 = isinstance(y, np.ndarray)
    if check_scalar1 == True or check_scalar2 == True or check_array1 == True and check_array2 == True and x.shape == y.shape:
        print("\nSum of the two arrays: ")
        print(x+y)
        print("\nDifference of two arrays: ")
        print(x-y)
        print("\nProduct of the two arrays: ")
        print(x*y)
        print("\nQuotient of the two arrays: ")
        print(x/y)
    elif check_array1 == True and check_array2 == True and x.shape != y.shape:
        print("\nCan't perform certain operations, Shapes of array should be equal.")

In [36]:
F = 2
G = np.array([[1,1,1],[9,1,9],[7,2,8]])
H = np.array([[1,5,1],[1,3,3],[1,5,5]])
I = np.array([[9,8,7],[7,5,6],[4,3,2],[2,4,6]])
J = np.array([[5,6,6],[3,2,1],[4,6,8]])

In [41]:
mat_operations(F,G)

Array 1: 
 2

Array 2: 
 [[1 1 1]
 [9 1 9]
 [7 2 8]]

Is Scalar(Array1):  True

Is Scalar(Array2):  False

Sum of the two arrays: 
[[ 3  3  3]
 [11  3 11]
 [ 9  4 10]]

Difference of two arrays: 
[[ 1  1  1]
 [-7  1 -7]
 [-5  0 -6]]

Product of the two arrays: 
[[ 2  2  2]
 [18  2 18]
 [14  4 16]]

Quotient of the two arrays: 
[[2.         2.         2.        ]
 [0.22222222 2.         0.22222222]
 [0.28571429 1.         0.25      ]]


In [42]:
mat_operations(G,H)

Array 1: 
 [[1 1 1]
 [9 1 9]
 [7 2 8]]

Array 2: 
 [[1 5 1]
 [1 3 3]
 [1 5 5]]

Is Scalar(Array1):  False

Is Scalar(Array2):  False

Sum of the two arrays: 
[[ 2  6  2]
 [10  4 12]
 [ 8  7 13]]

Difference of two arrays: 
[[ 0 -4  0]
 [ 8 -2  6]
 [ 6 -3  3]]

Product of the two arrays: 
[[ 1  5  1]
 [ 9  3 27]
 [ 7 10 40]]

Quotient of the two arrays: 
[[1.         0.2        1.        ]
 [9.         0.33333333 3.        ]
 [7.         0.4        1.6       ]]


In [43]:
mat_operations(H,I)

Array 1: 
 [[1 5 1]
 [1 3 3]
 [1 5 5]]

Array 2: 
 [[9 8 7]
 [7 5 6]
 [4 3 2]
 [2 4 6]]

Is Scalar(Array1):  False

Is Scalar(Array2):  False

Can't perform certain operations, Shapes of array should be equal.


In [40]:
mat_operations(I,J)

Array 1: 
 [[9 8 7]
 [7 5 6]
 [4 3 2]
 [2 4 6]]

Array 2: 
 [[5 6 6]
 [3 2 1]
 [4 6 8]]

Is Scalar(Array1):  False

Is Scalar(Array2):  False

Can't perform certain operations, Shapes of array should be equal.
